export const bus = [
  {
    id: 1,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "New York City, USA",
    destination: "Miami, USA",
    expense: 12,
    imageUrl: "/bus/1.jpg",
  },
  {
    id: 2,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Paris, France",
    destination: "Barcelona, Spain",
    expense: 8,
    imageUrl: "/bus/2.jpg",
  },
  {
    id: 3,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Sydney, Australia",
    destination: "Melbourne, Australia",
    expense: 5,
    imageUrl: "/bus/3.jpg",
  },
  {
    id: 4,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Tokyo, Japan",
    destination: "Kyoto, Japan",
    expense: 6,
    imageUrl: "/bus/4.jpg",
  },
  {
    id: 5,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Toronto, Canada",
    destination: "Montreal, Canada",
    expense: 4,
    imageUrl: "/bus/5.jpg",
  },
  {
    id: 6,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "San Francisco, USA",
    destination: "Los Angeles, USA",
    expense: 6,
    imageUrl: "/bus/6.jpg",
  },
  {
    id: 7,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Rome, Italy",
    destination: "Venice, Italy",
    expense: 7,
    imageUrl: "/bus/7.jpg",
  },
  {
    id: 8,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "London, UK",
    destination: "Edinburgh, UK",
    expense: 5,
    imageUrl: "/bus/8.jpg",
  },
  {
    id: 9,
    startDate: "09 Apr 2023",
    endDate: "11 Apr 2023",
    startLocation: "Cape Town, South Africa",
    destination: "Johannesburg, South Africa",
    expense: 6,
    imageUrl: "/bus/9.jpg",
  },
];
export const train = [
  {
    id: 1,
    startDate: "2023-04-12",
    endDate: "2023-04-15",
    startLocation: "Athens, Greece",
    destination: "Santorini, Greece",
    expense: 5,
    imageUrl: "/train/1.jpg",
  },
  {
    id: 2,
    startDate: "2023-05-06",
    endDate: "2023-05-09",
    startLocation: "Istanbul, Turkey",
    destination: "Cappadocia, Turkey",
    expense: 4,
    imageUrl: "/train/2.jpg",
  },
  {
    id: 3,
    startDate: "2023-03-27",
    endDate: "2023-03-29",
    startLocation: "Barcelona, Spain",
    destination: "Madrid, Spain",
    expense: 3,
    imageUrl: "/train/3.jpg",
  },
  {
    id: 4,
    startDate: "2023-04-19",
    endDate: "2023-04-22",
    startLocation: "Tokyo, Japan",
    destination: "Kyoto, Japan",
    expense: 5,
    imageUrl: "/train/4.jpg",
  },
];
